### PR TITLE
Update jenkins.yml to make GIT_* variables available

### PR DESCRIPTION
**Pull request by tylerauerbeck**
Adds GITHUB_USER and GITHUB_PASSWORD to jenkins.yml

### CODE REVIEW

**Comment by tylerauerbeck** [comment]
@oybed @logandonley

**Comment by oybed** [comment]
@tylerauerbeck as we're not using `GITHUB` for these, we probably should name the variables something a bit neutral - i.e.: `GIT_USERNAME` and `GIT_PASSWORD`. Thoughts?

**Comment by tylerauerbeck** [comment]
Yeah, this was definitely a mistake on my end when I was cleaning things up. This should be `GIT_USERNAME` and `GIT_PASSWORD`

**Comment by tylerauerbeck** [comment]
@oybed @logandonley Cleaned this up. Let me know if this looks good and we can merge.

**Review by logandonley — APPROVED** [review]

**Pull request merged**
